fix(TPRUN-5024) : remove camel-script-jruby feature
Talend/apache-camel pull request #91
Opened 2023-01-25 07:56 UTC by f2par0

🏁 **Context (Jira, design, ...)**
- https://jira.talendforge.org/browse/TPRUN-5024
- 
🔍 **What is the problem this PR is trying to solve?**
jruby embeds snakeyaml libraries with CVEs

🚀 **What is the chosen solution to this problem?**
Empty the feature (removal could cause hangs during update)

🎾 **Impacts**

- [ ] **This PR introduces a breaking change**

**Dear contributor, please check if the PR fulfills these requirements**

- [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

2023-01-25 11:00 UTC, andreasmattes requested changes
Addition of the CVE to be considered, the rest looks good.

2023-01-25 11:00 UTC, andreasmattes commented on platforms/karaf/features/src/main/resources/features.xml
> +    <!-- removed for security reasons -->
I suggest to add to the comment: "CVE-2022-25857 (high, snakeyaml included in jruby) and further medium CVEs". This clarifies better while this feature has been cleared.

2023-02-01 16:32 UTC, f2par0 commented on platforms/karaf/features/src/main/resources/features.xml
> +    <!-- removed for security reasons -->
Ok, done

2023-02-01 16:32 UTC, andreasmattes commented on platforms/karaf/features/src/main/resources/features.xml
> +    <!-- removed for security reasons -->
CVE reference is added.

2023-02-01 16:38 UTC, merged